In [1]:
import keras

Using TensorFlow backend.
/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

In [2]:
import pandas as pd
import numpy as np

In [3]:
concrete_data = pd.read_csv('https://cocl.us/concrete_data')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [4]:
concrete_data.shape

(1030, 9)

In [5]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [6]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [7]:
# there are approximately 1030 samples to train our model and data looks very clean to build the model since no missing values

In [8]:
# Split data into predictors and target
concrete_data_columns = concrete_data.columns
predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

In [9]:
predictors.head() # predictors table

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [10]:
target.head() # target table

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

In [18]:
n_cols = predictors_norm.shape[1] # number of predictors

In [19]:
# Import packages from the Keras library that we will need to build our regressoin model.
from keras.models import Sequential
from keras.layers import Dense

In [20]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [21]:
# build the model
model = regression_model()

In [23]:
# fit the model
model.fit(predictors_norm, target, validation_split=0.3, epochs=50, verbose=2)

Train on 721 samples, validate on 309 samples
Epoch 1/50
 - 0s - loss: 375.1714 - val_loss: 443.2298
Epoch 2/50
 - 0s - loss: 363.1013 - val_loss: 429.7414
Epoch 3/50
 - 0s - loss: 351.1755 - val_loss: 417.1340
Epoch 4/50
 - 0s - loss: 339.7089 - val_loss: 404.1198
Epoch 5/50
 - 0s - loss: 328.6848 - val_loss: 391.1525
Epoch 6/50
 - 0s - loss: 317.7675 - val_loss: 378.1118
Epoch 7/50
 - 0s - loss: 307.1452 - val_loss: 366.1102
Epoch 8/50
 - 0s - loss: 297.1564 - val_loss: 353.6740
Epoch 9/50
 - 0s - loss: 287.5609 - val_loss: 341.9728
Epoch 10/50
 - 0s - loss: 278.5130 - val_loss: 330.3406
Epoch 11/50
 - 0s - loss: 269.7992 - val_loss: 319.2341
Epoch 12/50
 - 0s - loss: 261.9514 - val_loss: 308.7888
Epoch 13/50
 - 0s - loss: 254.6010 - val_loss: 299.6097
Epoch 14/50
 - 0s - loss: 247.7092 - val_loss: 290.9592
Epoch 15/50
 - 0s - loss: 241.5992 - val_loss: 282.5300
Epoch 16/50
 - 0s - loss: 235.7505 - val_loss: 275.4143
Epoch 17/50
 - 0s - loss: 230.5867 - val_loss: 268.2737
Epoch 18/50
 - 0s - loss: 225.5914 - val_loss: 262.2228
Epoch 19/50
 - 0s - loss: 221.1854 - val_loss: 255.8664
Epoch 20/50
 - 0s - loss: 216.8866 - val_loss: 250.6504
Epoch 21/50
 - 0s - loss: 213.0318 - val_loss: 245.7613
Epoch 22/50
 - 0s - loss: 209.5517 - val_loss: 240.6970
Epoch 23/50
 - 0s - loss: 206.1070 - val_loss: 236.9225
Epoch 24/50
 - 0s - loss: 203.1110 - val_loss: 232.9716
Epoch 25/50
 - 0s - loss: 200.1095 - val_loss: 228.7172
Epoch 26/50
 - 0s - loss: 197.3563 - val_loss: 225.7616
Epoch 27/50
 - 0s - loss: 194.7826 - val_loss: 222.5786
Epoch 28/50
 - 0s - loss: 192.2996 - val_loss: 219.9990
Epoch 29/50
 - 0s - loss: 190.0790 - val_loss: 216.9018
Epoch 30/50
 - 0s - loss: 187.7526 - val_loss: 214.3865
Epoch 31/50
 - 0s - loss: 185.7045 - val_loss: 211.6405
Epoch 32/50
 - 0s - loss: 183.6615 - val_loss: 209.4919
Epoch 33/50
 - 0s - loss: 181.7889 - val_loss: 207.2028
Epoch 34/50
 - 0s - loss: 180.0405 - val_loss: 204.4216
Epoch 35/50
 - 0s - loss: 178.2936 - val_loss: 202.8897
Epoch 36/50
 - 0s - loss: 176.6829 - val_loss: 200.5127
Epoch 37/50
 - 0s - loss: 175.1264 - val_loss: 198.7111
Epoch 38/50
 - 0s - loss: 173.6644 - val_loss: 196.5719
Epoch 39/50
 - 0s - loss: 172.3085 - val_loss: 194.4880
Epoch 40/50
 - 0s - loss: 171.0478 - val_loss: 192.2389
Epoch 41/50
 - 0s - loss: 169.7558 - val_loss: 189.8664
Epoch 42/50
 - 0s - loss: 168.5150 - val_loss: 188.6155
Epoch 43/50
 - 0s - loss: 167.3789 - val_loss: 187.0900
Epoch 44/50
 - 0s - loss: 166.2395 - val_loss: 184.6812
Epoch 45/50
 - 0s - loss: 165.0140 - val_loss: 183.2411
Epoch 46/50
 - 0s - loss: 163.9500 - val_loss: 181.6680
Epoch 47/50
 - 0s - loss: 162.8580 - val_loss: 180.2072
Epoch 48/50
 - 0s - loss: 161.8293 - val_loss: 178.6628
Epoch 49/50
 - 0s - loss: 160.8086 - val_loss: 177.3795
Epoch 50/50
 - 0s - loss: 159.8929 - val_loss: 176.3162

In [24]:
# Data Normalization by substracting the mean and dividing by the standard deviation.
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [25]:
# fit the model with normalized data
model.fit(predictors_norm, target, validation_split=0.3, epochs=50, verbose=2)

Train on 721 samples, validate on 309 samples
Epoch 1/50
 - 0s - loss: 158.8788 - val_loss: 174.7276
Epoch 2/50
 - 0s - loss: 157.9913 - val_loss: 172.9576
Epoch 3/50
 - 0s - loss: 157.0865 - val_loss: 171.8067
Epoch 4/50
 - 0s - loss: 156.1961 - val_loss: 170.3852
Epoch 5/50
 - 0s - loss: 155.3665 - val_loss: 168.7171
Epoch 6/50
 - 0s - loss: 154.4327 - val_loss: 167.6033
Epoch 7/50
 - 0s - loss: 153.6669 - val_loss: 166.8338
Epoch 8/50
 - 0s - loss: 152.7763 - val_loss: 165.3727
Epoch 9/50
 - 0s - loss: 151.9640 - val_loss: 164.1814
Epoch 10/50
 - 0s - loss: 151.1665 - val_loss: 162.9324
Epoch 11/50
 - 0s - loss: 150.3310 - val_loss: 161.8587
Epoch 12/50
 - 0s - loss: 149.5854 - val_loss: 160.5680
Epoch 13/50
 - 0s - loss: 148.7921 - val_loss: 159.6229
Epoch 14/50
 - 0s - loss: 148.0552 - val_loss: 158.4651
Epoch 15/50
 - 0s - loss: 147.2914 - val_loss: 157.1787
Epoch 16/50
 - 0s - loss: 146.5681 - val_loss: 156.5693
Epoch 17/50
 - 0s - loss: 145.7113 - val_loss: 155.7283
Epoch 18/50
 - 0s - loss: 145.1206 - val_loss: 154.7347
Epoch 19/50
 - 0s - loss: 144.3071 - val_loss: 153.3261
Epoch 20/50
 - 0s - loss: 143.5772 - val_loss: 152.4283
Epoch 21/50
 - 0s - loss: 142.8369 - val_loss: 151.9773
Epoch 22/50
 - 0s - loss: 142.1592 - val_loss: 150.8989
Epoch 23/50
 - 0s - loss: 141.3538 - val_loss: 150.2030
Epoch 24/50
 - 0s - loss: 140.6895 - val_loss: 149.0892
Epoch 25/50
 - 0s - loss: 139.9311 - val_loss: 148.2629
Epoch 26/50
 - 0s - loss: 139.1837 - val_loss: 147.0543
Epoch 27/50
 - 0s - loss: 138.4907 - val_loss: 146.1626
Epoch 28/50
 - 0s - loss: 137.8157 - val_loss: 145.1972
Epoch 29/50
 - 0s - loss: 137.1683 - val_loss: 144.5195
Epoch 30/50
 - 0s - loss: 136.4937 - val_loss: 143.6175
Epoch 31/50
 - 0s - loss: 135.8278 - val_loss: 143.4895
Epoch 32/50
 - 0s - loss: 135.0800 - val_loss: 142.5411
Epoch 33/50
 - 0s - loss: 134.5127 - val_loss: 141.8294
Epoch 34/50
 - 0s - loss: 133.7116 - val_loss: 141.3145
Epoch 35/50
 - 0s - loss: 133.1852 - val_loss: 140.2634
Epoch 36/50
 - 0s - loss: 132.5376 - val_loss: 140.0785
Epoch 37/50
 - 0s - loss: 131.8145 - val_loss: 139.8542
Epoch 38/50
 - 0s - loss: 131.1778 - val_loss: 139.2916
Epoch 39/50
 - 0s - loss: 130.6149 - val_loss: 138.8125
Epoch 40/50
 - 0s - loss: 129.9797 - val_loss: 137.8955
Epoch 41/50
 - 0s - loss: 129.4092 - val_loss: 137.2245
Epoch 42/50
 - 0s - loss: 128.7020 - val_loss: 136.6290
Epoch 43/50
 - 0s - loss: 128.0760 - val_loss: 136.1886
Epoch 44/50
 - 0s - loss: 127.4842 - val_loss: 135.7791
Epoch 45/50
 - 0s - loss: 126.9756 - val_loss: 135.1894
Epoch 46/50
 - 0s - loss: 126.3752 - val_loss: 134.3428
Epoch 47/50
 - 0s - loss: 125.8163 - val_loss: 133.6155
Epoch 48/50
 - 0s - loss: 125.2297 - val_loss: 133.9092
Epoch 49/50
 - 0s - loss: 124.7287 - val_loss: 133.4714
Epoch 50/50
 - 0s - loss: 124.0904 - val_loss: 132.6215

In [26]:
# fit the model with normalized data and increasing the epochs number from 50 to 100
model.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

Train on 721 samples, validate on 309 samples
Epoch 1/100
 - 0s - loss: 123.5101 - val_loss: 132.4333
Epoch 2/100
 - 0s - loss: 123.1276 - val_loss: 132.3533
Epoch 3/100
 - 0s - loss: 122.4519 - val_loss: 131.3823
Epoch 4/100
 - 0s - loss: 121.9505 - val_loss: 130.9756
Epoch 5/100
 - 0s - loss: 121.5242 - val_loss: 130.8873
Epoch 6/100
 - 0s - loss: 120.8892 - val_loss: 129.9877
Epoch 7/100
 - 0s - loss: 120.3368 - val_loss: 130.0049
Epoch 8/100
 - 0s - loss: 119.8162 - val_loss: 129.4686
Epoch 9/100
 - 0s - loss: 119.2785 - val_loss: 129.6930
Epoch 10/100
 - 0s - loss: 118.7787 - val_loss: 128.8816
Epoch 11/100
 - 0s - loss: 118.1894 - val_loss: 128.6890
Epoch 12/100
 - 0s - loss: 117.6846 - val_loss: 128.1739
Epoch 13/100
 - 0s - loss: 117.1862 - val_loss: 127.7868
Epoch 14/100
 - 0s - loss: 116.6987 - val_loss: 127.4447
Epoch 15/100
 - 0s - loss: 116.1654 - val_loss: 126.9634
Epoch 16/100
 - 0s - loss: 115.6767 - val_loss: 126.5209
Epoch 17/100
 - 0s - loss: 115.2428 - val_loss: 126.6341
Epoch 18/100
 - 0s - loss: 114.8568 - val_loss: 125.9622
Epoch 19/100
 - 0s - loss: 114.1432 - val_loss: 125.8406
Epoch 20/100
 - 0s - loss: 113.7914 - val_loss: 125.1736
Epoch 21/100
 - 0s - loss: 113.2478 - val_loss: 124.7282
Epoch 22/100
 - 0s - loss: 112.8224 - val_loss: 125.0892
Epoch 23/100
 - 0s - loss: 112.3507 - val_loss: 124.5190
Epoch 24/100
 - 0s - loss: 111.8611 - val_loss: 124.4794
Epoch 25/100
 - 0s - loss: 111.3090 - val_loss: 124.1457
Epoch 26/100
 - 0s - loss: 110.9455 - val_loss: 123.3353
Epoch 27/100
 - 0s - loss: 110.4383 - val_loss: 123.2584
Epoch 28/100
 - 0s - loss: 110.1045 - val_loss: 122.8610
Epoch 29/100
 - 0s - loss: 109.5741 - val_loss: 123.1953
Epoch 30/100
 - 0s - loss: 109.1704 - val_loss: 122.5302
Epoch 31/100
 - 0s - loss: 108.7305 - val_loss: 122.3020
Epoch 32/100
 - 0s - loss: 108.2937 - val_loss: 121.9667
Epoch 33/100
 - 0s - loss: 107.8638 - val_loss: 121.8043
Epoch 34/100
 - 0s - loss: 107.4915 - val_loss: 121.5897
Epoch 35/100
 - 0s - loss: 107.0223 - val_loss: 121.6624
Epoch 36/100
 - 0s - loss: 106.6648 - val_loss: 120.8897
Epoch 37/100
 - 0s - loss: 106.2120 - val_loss: 121.0516
Epoch 38/100
 - 0s - loss: 105.8615 - val_loss: 120.7506
Epoch 39/100
 - 0s - loss: 105.5037 - val_loss: 120.5842
Epoch 40/100
 - 0s - loss: 105.1616 - val_loss: 120.5880
Epoch 41/100
 - 0s - loss: 104.7321 - val_loss: 120.1628
Epoch 42/100
 - 0s - loss: 104.4237 - val_loss: 119.6578
Epoch 43/100
 - 0s - loss: 103.9460 - val_loss: 119.3757
Epoch 44/100
 - 0s - loss: 103.7245 - val_loss: 119.7929
Epoch 45/100
 - 0s - loss: 103.2699 - val_loss: 119.0561
Epoch 46/100
 - 0s - loss: 103.0035 - val_loss: 118.5891
Epoch 47/100
 - 0s - loss: 102.6942 - val_loss: 118.6181
Epoch 48/100
 - 0s - loss: 102.2087 - val_loss: 118.6868
Epoch 49/100
 - 0s - loss: 101.9161 - val_loss: 118.5427
Epoch 50/100
 - 0s - loss: 101.5436 - val_loss: 118.3135
Epoch 51/100
 - 0s - loss: 101.2319 - val_loss: 118.3834
Epoch 52/100
 - 0s - loss: 100.9650 - val_loss: 117.7345
Epoch 53/100
 - 0s - loss: 100.5425 - val_loss: 118.0481
Epoch 54/100
 - 0s - loss: 100.2032 - val_loss: 117.4028
Epoch 55/100
 - 0s - loss: 99.8684 - val_loss: 117.2395
Epoch 56/100
 - 0s - loss: 99.5401 - val_loss: 117.4570
Epoch 57/100
 - 0s - loss: 99.2341 - val_loss: 117.3315
Epoch 58/100
 - 0s - loss: 98.9084 - val_loss: 117.2682
Epoch 59/100
 - 0s - loss: 98.7123 - val_loss: 116.4957
Epoch 60/100
 - 0s - loss: 98.3090 - val_loss: 116.8041
Epoch 61/100
 - 0s - loss: 98.0050 - val_loss: 116.6468
Epoch 62/100
 - 0s - loss: 97.7764 - val_loss: 116.4034
Epoch 63/100
 - 0s - loss: 97.4435 - val_loss: 116.7551
Epoch 64/100
 - 0s - loss: 97.2065 - val_loss: 116.5354
Epoch 65/100
 - 0s - loss: 96.9161 - val_loss: 115.9328
Epoch 66/100
 - 0s - loss: 96.6344 - val_loss: 116.1982
Epoch 67/100
 - 0s - loss: 96.2908 - val_loss: 116.2232
Epoch 68/100
 - 0s - loss: 96.1344 - val_loss: 116.3679
Epoch 69/100
 - 0s - loss: 95.8228 - val_loss: 115.4084
Epoch 70/100
 - 0s - loss: 95.5442 - val_loss: 115.4587
Epoch 71/100
 - 0s - loss: 95.2382 - val_loss: 115.2085
Epoch 72/100
 - 0s - loss: 95.0282 - val_loss: 115.0208
Epoch 73/100
 - 0s - loss: 94.7416 - val_loss: 115.0906
Epoch 74/100
 - 0s - loss: 94.5333 - val_loss: 115.1184
Epoch 75/100
 - 0s - loss: 94.2798 - val_loss: 114.7649
Epoch 76/100
 - 0s - loss: 94.1744 - val_loss: 114.9552
Epoch 77/100
 - 0s - loss: 93.8937 - val_loss: 114.4841
Epoch 78/100
 - 0s - loss: 93.6122 - val_loss: 114.5745
Epoch 79/100
 - 0s - loss: 93.3288 - val_loss: 114.5373
Epoch 80/100
 - 0s - loss: 93.1713 - val_loss: 114.9980
Epoch 81/100
 - 0s - loss: 92.9355 - val_loss: 114.3254
Epoch 82/100
 - 0s - loss: 92.7101 - val_loss: 114.2914
Epoch 83/100
 - 0s - loss: 92.5284 - val_loss: 114.3676
Epoch 84/100
 - 0s - loss: 92.2261 - val_loss: 114.2561
Epoch 85/100
 - 0s - loss: 92.0417 - val_loss: 114.1432
Epoch 86/100
 - 0s - loss: 91.8012 - val_loss: 114.0228
Epoch 87/100
 - 0s - loss: 91.6073 - val_loss: 113.7040
Epoch 88/100
 - 0s - loss: 91.4194 - val_loss: 114.0718
Epoch 89/100
 - 0s - loss: 91.2687 - val_loss: 114.1461
Epoch 90/100
 - 0s - loss: 91.1425 - val_loss: 113.8747
Epoch 91/100
 - 0s - loss: 90.8388 - val_loss: 113.5155
Epoch 92/100
 - 0s - loss: 90.5929 - val_loss: 113.4568
Epoch 93/100
 - 0s - loss: 90.4416 - val_loss: 114.0811
Epoch 94/100
 - 0s - loss: 90.2220 - val_loss: 113.7368
Epoch 95/100
 - 0s - loss: 90.1319 - val_loss: 113.3691
Epoch 96/100
 - 0s - loss: 89.8657 - val_loss: 113.3344
Epoch 97/100
 - 0s - loss: 89.7031 - val_loss: 113.2674
Epoch 98/100
 - 0s - loss: 89.5099 - val_loss: 113.1831
Epoch 99/100
 - 0s - loss: 89.3975 - val_loss: 113.3218
Epoch 100/100
 - 0s - loss: 89.2103 - val_loss: 113.1685

In [32]:
# define a new regression model with three hidden layers, each of 10 nodes and ReLU activation function
def regression_model1():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(1))
    
    # compile model1
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [33]:
# build the model
model = regression_model1()

In [34]:
# fit the model with normalized data with epocks=50 and with the new regression model built with 3 hidden layers made up of 10 nodes each of them
model.fit(predictors_norm, target, validation_split=0.3, epochs=50, verbose=2)

Train on 721 samples, validate on 309 samples
Epoch 1/50
 - 0s - loss: 1694.7099 - val_loss: 1219.1602
Epoch 2/50
 - 0s - loss: 1667.5643 - val_loss: 1196.9947
Epoch 3/50
 - 0s - loss: 1634.2100 - val_loss: 1168.8913
Epoch 4/50
 - 0s - loss: 1585.5531 - val_loss: 1126.4044
Epoch 5/50
 - 0s - loss: 1507.3752 - val_loss: 1060.7152
Epoch 6/50
 - 0s - loss: 1375.9352 - val_loss: 954.1788
Epoch 7/50
 - 0s - loss: 1167.9463 - val_loss: 795.0599
Epoch 8/50
 - 0s - loss: 886.0237 - val_loss: 601.2821
Epoch 9/50
 - 0s - loss: 591.5402 - val_loss: 412.3746
Epoch 10/50
 - 0s - loss: 372.8084 - val_loss: 283.5571
Epoch 11/50
 - 0s - loss: 272.8048 - val_loss: 215.7787
Epoch 12/50
 - 0s - loss: 237.6739 - val_loss: 188.2718
Epoch 13/50
 - 0s - loss: 220.2777 - val_loss: 174.8963
Epoch 14/50
 - 0s - loss: 209.8196 - val_loss: 167.2027
Epoch 15/50
 - 0s - loss: 202.4933 - val_loss: 161.5049
Epoch 16/50
 - 0s - loss: 196.3322 - val_loss: 159.0097
Epoch 17/50
 - 0s - loss: 191.7915 - val_loss: 156.4758
Epoch 18/50
 - 0s - loss: 188.1713 - val_loss: 156.2111
Epoch 19/50
 - 0s - loss: 184.6722 - val_loss: 154.6273
Epoch 20/50
 - 0s - loss: 181.6586 - val_loss: 152.8578
Epoch 21/50
 - 0s - loss: 178.8330 - val_loss: 151.5526
Epoch 22/50
 - 0s - loss: 176.7355 - val_loss: 151.6570
Epoch 23/50
 - 0s - loss: 174.5603 - val_loss: 151.4819
Epoch 24/50
 - 0s - loss: 172.0292 - val_loss: 150.4763
Epoch 25/50
 - 0s - loss: 170.3158 - val_loss: 150.3690
Epoch 26/50
 - 0s - loss: 169.0194 - val_loss: 151.2863
Epoch 27/50
 - 0s - loss: 166.9222 - val_loss: 149.0715
Epoch 28/50
 - 0s - loss: 164.9454 - val_loss: 147.4238
Epoch 29/50
 - 0s - loss: 163.6279 - val_loss: 148.5649
Epoch 30/50
 - 0s - loss: 161.9359 - val_loss: 148.1694
Epoch 31/50
 - 0s - loss: 160.9821 - val_loss: 148.2683
Epoch 32/50
 - 0s - loss: 159.4112 - val_loss: 147.7708
Epoch 33/50
 - 0s - loss: 158.4462 - val_loss: 147.5356
Epoch 34/50
 - 0s - loss: 157.0325 - val_loss: 146.8252
Epoch 35/50
 - 0s - loss: 155.8966 - val_loss: 148.0304
Epoch 36/50
 - 0s - loss: 155.7690 - val_loss: 147.0727
Epoch 37/50
 - 0s - loss: 153.8131 - val_loss: 146.2433
Epoch 38/50
 - 0s - loss: 153.0327 - val_loss: 148.7670
Epoch 39/50
 - 0s - loss: 152.1370 - val_loss: 146.3323
Epoch 40/50
 - 0s - loss: 152.0519 - val_loss: 147.3535
Epoch 41/50
 - 0s - loss: 150.6622 - val_loss: 145.3268
Epoch 42/50
 - 0s - loss: 149.9135 - val_loss: 147.1426
Epoch 43/50
 - 0s - loss: 148.8374 - val_loss: 144.6818
Epoch 44/50
 - 0s - loss: 147.9620 - val_loss: 145.9993
Epoch 45/50
 - 0s - loss: 147.2498 - val_loss: 145.7908
Epoch 46/50
 - 0s - loss: 146.6332 - val_loss: 144.9295
Epoch 47/50
 - 0s - loss: 145.9583 - val_loss: 145.2111
Epoch 48/50
 - 0s - loss: 145.4771 - val_loss: 145.1348
Epoch 49/50
 - 0s - loss: 144.5182 - val_loss: 144.8040
Epoch 50/50
 - 0s - loss: 143.6710 - val_loss: 144.7836